ingredients_list = [
    "All-purpose flour",
    "Baking powder",
    "Baking soda",
    "Salt",
    "Sugar",
    "Brown sugar",
    "Powdered sugar",
    "Vanilla extract",
    "Eggs",
    "Milk",
    "Buttermilk",
    "Heavy cream",
    "Butter",
    "Olive oil",
    "Vegetable oil",
    "Canola oil",
    "Yeast",
    "Cocoa powder",
    "Chocolate chips",
    "White chocolate",
    "Peanut butter",
    "Almonds",
    "Walnuts",
    "Pecans",
    "Hazelnuts",
    "Oats",
    "Rice",
    "Pasta",
    "Tomatoes",
    "Tomato paste",
    "Tomato sauce",
    "Chicken broth",
    "Beef broth",
    "Vegetable broth",
    "Soy sauce",
    "Worcestershire sauce",
    "Hot sauce",
    "Vinegar",
    "Balsamic vinegar",
    "Rice vinegar",
    "Apple cider vinegar",
    "Garlic",
    "Onions",
    "Carrots",
    "Celery",
    "Bell peppers",
    "Broccoli",
    "Spinach",
    "Lettuce",
    "Kale",
    "Potatoes",
    "Sweet potatoes",
    "Zucchini",
    "Cucumber",
    "Mushrooms",
    "Green beans",
    "Peas",
    "Corn",
    "Lemons",
    "Limes",
    "Oranges",
    "Bananas",
    "Apples",
    "Berries",
    "Watermelon",
    "Chicken breasts",
    "Chicken thighs",
    "Ground beef",
    "Steak",
    "Pork chops",
    "Bacon",
    "Sausage",
    "Ham",
    "Salmon",
    "Shrimp",
    "Tilapia",
    "Tofu",
    "Cheddar cheese",
    "Mozzarella cheese",
    "Parmesan cheese",
    "Feta cheese",
    "Goat cheese",
    "Yogurt",
    "Cream cheese",
    "Sour cream",
    "Eggplant",
    "Avocado",
    "Coconut milk",
    "Almond milk",
    "Soy milk",
    "Honey",
    "Maple syrup",
    "Mustard",
    "Ketchup",
    "Mayonnaise",
    "Bread",
    "Bread crumbs",
    "Panko",
    "Raisins",
    "Dates",
    "Flaxseed",
    "Chia seeds",
    "Chicken",
    "Beef",
    "Pork",
    "Turkey",
    "Salmon",
    "Tuna",
    "Shrimp",
    "Tofu",
    "Quinoa",
    "Rice",
    "Pasta",
    "Broccoli",
    "Spinach",
    "Kale",
    "Garlic",
    "Onions",
    "Tomatoes",
    "Potatoes",
    "Carrots",
    "Bell Peppers",
    "Mushrooms",
    "Zucchini",
    "Cucumber",
    "Apples",
    "Bananas",
    "Oranges",
    "Berries",
    "Lemons",
    "Avocados",
    "Almonds",
    "Peanuts",
    "Cashews",
    "Walnuts",
    "Olive Oil",
    "Butter",
    "Coconut Oil",
    "Cheese",
    "Milk",
    "Yogurt",
    "Eggs",
    "Basil",
    "Cilantro",
    "Rosemary",
    "Thyme",
    "Oregano",
    "Paprika",
    "Saffron",
    "Turmeric",
    "Cumin",
    "Cinnamon",
    "Ginger",
    "Maple Syrup",
    "Buckwheat",
    "Lentils",
    "Chickpeas",
    "Black Beans",
    "Sweet Potatoes",
    "Chia Seeds",
    "Flaxseeds",
    "Honey",
    "Agave Nectar",
    "Oats",
    "Almond Milk",
    "Soy Milk",
    "Rice Milk",
    "Coconut Milk",
    "Tempeh",
    "Seitan",
    "Nutritional Yeast",
    "Soy Sauce"
]
