"""Rename ingredient_diet to restricted_diet_ingredients

Revision ID: 6bc3e4da3b6c
Revises: 7f90902c8773
Create Date: 2024-02-21 07:48:49.564184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bc3e4da3b6c'
down_revision = '7f90902c8773'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restricted_diet_ingredient',
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('diet_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['diet_id'], ['diet.id'], ),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ),
    sa.PrimaryKeyConstraint('ingredient_id', 'diet_id')
    )
    op.drop_table('ingredient_diet')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredient_diet',
    sa.Column('ingredient_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('diet_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['diet_id'], ['diet.id'], name='ingredient_diet_diet_id_fkey'),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], name='ingredient_diet_ingredient_id_fkey'),
    sa.PrimaryKeyConstraint('ingredient_id', 'diet_id', name='ingredient_diet_pkey')
    )
    op.drop_table('restricted_diet_ingredient')
    # ### end Alembic commands ###
